-- Add extra fields to empresas table (safe: IF NOT EXISTS)
ALTER TABLE empresas
  ADD COLUMN IF NOT EXISTS ruc VARCHAR(50),
  ADD COLUMN IF NOT EXISTS direccion VARCHAR(255),
  ADD COLUMN IF NOT EXISTS ciudad VARCHAR(100),
  ADD COLUMN IF NOT EXISTS razon_social VARCHAR(255),
  ADD COLUMN IF NOT EXISTS provincia VARCHAR(100),
  ADD COLUMN IF NOT EXISTS telefono VARCHAR(50),
  ADD COLUMN IF NOT EXISTS email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS contacto_nombre VARCHAR(255),
  ADD COLUMN IF NOT EXISTS contacto_telefono VARCHAR(50),
  ADD COLUMN IF NOT EXISTS contacto_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS tipo_empresa VARCHAR(100);
